export enum EnumData {
    /*Request Category Enum */
    REQUEST_CATEGORY_ENUM_NETWORK_FACILITY = 1,
    REQUEST_CATEGORY_ENUM_ECLIPSE_MODULE = 2,
    REQUEST_CATEGORY_ENUM_REPORTING_SERVICE = 3,
    REQUEST_CATEGORY_ENUM_E_FINANCE = 4,
    REQUEST_CATEGORY_ENUM_BRANCH_CHANGE = 5,
    REQUEST_CATEGORY_ENUM_VPN_REQUEST = 6,
    REQUEST_CATEGORY_ENUM_E_LEARNING = 7,
    REQUEST_CATEGORY_ENUM_I_CARD = 8,
    REQUEST_CATEGORY_ENUM_KIBANA = 9,
    REQUEST_CATEGORY_ENUM_KTMS = 10,
    REQUEST_CATEGORY_ENUM_DATA_SCAN = 11,
    REQUEST_CATEGORY_ENUM_UAM_REQUEST = 12,
    REQUEST_CATEGORY_ENUM_CIM = 13,
    REQUEST_CATEGORY_ENUM_BOARD_PAC = 14,
    REQUEST_CATEGORY_ENUM_CDM = 15,
    REQUEST_CATEGORY_ENUM_DB_AND_ACTION_REQUEST = 16,
    REQUEST_CATEGORY_ENUM_CRM = 17,
    REQUEST_CATEGORY_ENUM_RESIGNATION_REQUEST = 18,
    REQUEST_CATEGORY_ENUM_CLEARANCE = 330,
    REQUEST_CATEGORY_ENUM_ORACL = 943,

    /* Request Category Enum Tab */
    REQUEST_CATEGORY_ENUM_HOD_TAB = 332,
    REQUEST_CATEGORY_ENUM_FINANCE_TAB = 334,
    REQUEST_CATEGORY_ENUM_CREDIT_TAB = 335,
    REQUEST_CATEGORY_ENUM_RECOVERIES_TAB = 336,
    REQUEST_CATEGORY_ENUM_GOLD_LOAN_TAB = 338,
    REQUEST_CATEGORY_ENUM_INTERNAL_AUDIT_TAB = 339,
    REQUEST_CATEGORY_ENUM_IT_TAB = 340,
    REQUEST_CATEGORY_ENUM_ADMIN_TAB = 341,
    REQUEST_CATEGORY_ENUM_HR_TAB = 342,
    REQUEST_CATEGORY_ENUM_ATTACHMENTS_TAB = 556,
    REQUEST_CATEGORY_ENUM_FINAL_APPROVAL_TAB = 333,

    NETWORK_FACILITY_ACTIVE_TYPE_INDEX = 19,
    NETWORK_FACILITY_ACTIVE_ACCORDIAN_INDEX = 18,
    /* Network Facility Request Enum tab */
    REQUEST_CATEGORY_ENUM_EMAIL_ACCESS = 19,
    REQUEST_CATEGORY_ENUM_FILE_SHARE = 20,
    REQUEST_CATEGORY_ENUM_AZURE_DEVOPS = 21,
    REQUEST_CATEGORY_ENUM_SERVER_ACCESS = 22,
    REQUEST_CATEGORY_ENUM_SOFTWARE_INSTALLATION = 23,
    REQUEST_CATEGORY_ENUM_INTERNET = 24,
    REQUEST_CATEGORY_ENUM_OTHER = 25,

    /* Network Facility => Server Access Request Types */
    SERVER_ACCESS_REPORTING_SERVER = 43,
    SERVER_ACCESS_HOSTING_SERVER = 44,
    SERVER_ACCESS_AD_SERVER = 45,
    SERVER_ACCESS_DB_SERVER = 46,
    SERVER_ACCESS_OTHER = 47,

    /* Eclipse Module Request Types */
    CASHIER_MODULE = 1,
    CENTRAL_MODULE = 2,
    CREDIT_MODULE = 3,
    CRIB_MANAGEMENT_MODULE = 4,
    DEPOSIT_MODULE = 5,
    GOLD_LOAN_MODULE = 6,
    WORKBENCH_MODULE = 7,
    MONEY_EXCHANGE_MODULE = 8,
    WESTERN_UNION_MODULE = 9,

    // ACCESS_REQUEST_DB_AND_ACTION_REQUEST
    MS_SQL = 1,
    MONGO_DB = 2,

    /* Resignation Steps */
    RESIGNATION_REQUEST = 0,
    EXIT_INTERVIEW = 1,
    CLEARANCE = 2,

    REQUEST_ENUM_OTHER_REQUEST = 2,

    /*Page index*/
    HOD_TAB = 0,
    FINANCE_TAB = 1,
    CREDIT_TAB = 2,
    RECOVERIES_TAB = 3,
    GOLD_LOAN_TAB = 4,
    INTERNAL_AUDIT_TAB = 5,
    IT_TAB = 6,
    ADMIN_TAB = 7,
    HR_TAB = 8,
    ATTACHMENT_TAB = 9,
    FINAL_APPROVAL_TAB = 10,
    
    /*Request CategoryEnum Department Id*/
    PAGE_ID_HOD = 14,
    PAGE_ID_FINANCE = 15,
    PAGE_ID_CREDIT = 16,
    PAGE_ID_RECOVERIES = 17,
    PAGE_ID_GOLD_LOAN = 18,
    PAGE_ID_INTERNAL_AUDIT = 19,
    PAGE_ID_IT = 20,
    PAGE_ID_ADMIN = 21,
    PAGE_ID_HR = 22,
    PAGE_ID_ATTACHMENTS = 23,
    PAGE_ID_FINAL_APPROVAL = 24,

    /*Document Types*/
    DOCUMENT_TYPE_ENUM_MY_BSP_ATTACHMENT = 1,
    DOCUMENT_TYPE_ENUM_HR_BSP_ATTACHMENT = 2,
    DOCUMENT_TYPE_ENUM_FIXED_ASSET_TRANSFER_LETTER_ATTACHMENT = 3,
    DOCUMENT_TYPE_ENUM_RESIGNATION_LETTER_ATTACHMENT = 4,

    /*Officer Mapping Category Id*/
    OFFICER_MAPPING_CATEGORY_ID_BSP_ATTACHMENT = 560,
    OFFICER_MAPPING_CATEGORY_ID_MY_BSP_ATTACHMENT = 562,
    OFFICER_MAPPING_CATEGORY_ID_HR_BSP_ATTACHMENT = 563,
    OFFICER_MAPPING_CATEGORY_ID_FIXED_ASSET_TRANSFER_LETTER_ATTACHMENT = 561,

    /*Request Types*/
    ACCESS_REQUEST_ENUM = 1,
    OTHER_REQUEST_ENUM = 2,
    
    //Rate Enum
    EXCELLENT = 1,
    VERY_GOOD = 2,
    GOOD = 3,
    AVERAGE = 4,
    POOR = 5,

    //Officer Type
    DIRECT = 1,
    INDIRECT =2,

    //Approval choice Enum
    APPROVAL_CHOICE_ENUM_NOT_APPLICABLE = 1,
    APPROVAL_CHOICE_ENUM_COMPLETE = 2,
    APPROVAL_CHOICE_ENUM_IN_COMPLETE = 3,

    EXIT_INTERVIEW_ANSWER_TYPE_ENUM_THREE_SELECT = 1,
    EXIT_INTERVIEW_ANSWER_TYPE_ENUM_TWO_SELECT = 2,
    EXIT_INTERVIEW_ANSWER_TYPE_ENUM_WRITTEN = 3,

    CLEARANCE_DEPARTMENT_ENUM_CREDIT = 558,
    //Department Enum
    INFORMATION_TECHNOLOGY_ENUM = 10,
    
    // Software Type Enum
    IT_USER_AUTHORIZED_SOFTWARE_ENUM = 39,
    IT_USER_UN_AUTHORIZED_SOFTWARE_ENUM = 41,
    
    NON_IT_USER_AUTHORIZED_SOFTWARE_ENUM = 40,
    NON_IT_USER_UN_AUTHORIZED_SOFTWARE_ENUM = 42,

    UN_AUTHORIZED_IT_USER_OTHER_SOFTWARE_ENUM = 707,
    UN_AUTHORIZED_NON_IT_USER_OTHER_SOFTWARE_ENUM = 708,

    APPROVAL_STATUS_ENUM_ASSIGNED = 10,
    APPROVAL_STATUS_ENUM_APPROVED = 2,

    CLEARANCE_TYPE_ENUM_CLEARANCE_DEPARTMENTS = 331,
    CLEARANCE_TYPE_ENUM_HOD_APPROVAL = 332,
    CLEARANCE_TYPE_ENUM_FINAL_APPROVAL = 333,
    CLEARANCE_TYPE_ENUM_HR_VRIFICATION = 566,

    // for officer mapping tab
    CLEARANCE_TYPE_ENUM_HR_VRIFICATION_TAB = 565,

    //User Type
    IT_USER = 34,
    DEFAULT_USER = 35,
    PRIVILEGE_USER = 36,
    IT_DEPARTMENT_ID = 10,

    //Tab Index
    EMAIL_ACCESS_TAB = 0,
    FILE_SHARE_ACCESS_TAB = 1,
    AZURE_DEVOPS_ACCESS_TAB = 2,
    SERVER_ACCESS_TAB = 3,
    SOFTWARE_INSTALLATION_TAB = 4,
    INTERNET_ACCESS_TAB = 5,
    OTHER_ACCESS_TAB = 6,

    //KTMS Sybsystem Enums
    KTMS_SYSTEM_ENUM = 1,    
    KTMS_GROUP_ENUM = 2,    
    KTMS_CATEGORY_ENUM = 3,

    //Approval Level
    NOT_APPROVED = 1,
    APPROVED = 2,

    // CIM Portals
    ADMIN_PORTAL = 711,
    AGENT_PORTAL = 712,

    //Action Types
    ACTION_TYPE_ENUM_APPROVE = 1,
    ACTION_TYPE_ENUM_REJECT = 2,
    ACTION_TYPE_ENUM_HOLD = 3,

    // Network Facility Request Type
    REQUEST_CATEGORY_ENUM_IT_USER = 34,
    REQUEST_CATEGORY_ENUM_DEFAULT_USER = 35,
    REQUEST_CATEGORY_ENUM_PRIVILEGE_USER = 36,
    
    REQUEST_CATEGORY_ENUM_INTERNAL_EMAIL = 26,
    REQUEST_CATEGORY_ENUM_EXTERNAL_EMAIL = 27,

    //DataScan Subtype Enums
    DATA_SCAN_PORTAL_TYPE_ENUM = 2,

    REQUEST_CATEGORY_ENUM_USB_ACCESS = 28,
    REQUEST_CATEGORY_ENUM_EXTERNAL_CD_ROM = 29,
    REQUEST_CATEGORY_ENUM_USB_ACCESS_READ = 30,
    REQUEST_CATEGORY_ENUM_EXTERNAL_CD_ROM_READ = 32,

    //Approval Status Enum
    MPT_APPROVAL_STATUS_ENUM_NA = 1,
    MPT_APPROVAL_STATUS_ENUM_APPROVED = 2,
    MPT_APPROVAL_STATUS_ENUM_NA_1ST_APPROVED = 3,
    MPT_APPROVAL_STATUS_ENUM_NA_2ND_APPROVED = 4,
    MPT_APPROVAL_STATUS_ENUM_NA_3RD_APPROVED = 5,
    MPT_APPROVAL_STATUS_ENUM_NA_4TH_APPROVED = 6,
    MPT_APPROVAL_STATUS_ENUM_APPROVAL_PENDING = 7,
    MPT_APPROVAL_STATUS_ENUM_VERIFICATION_PENDING = 8,
    MPT_APPROVAL_STATUS_ENUM_VERIFIED = 9,
    MPT_APPROVAL_STATUS_ENUM_ASSIGNED = 10,
    MPT_APPROVAL_STATUS_ENUM_APPROVAL_REJECT = 11,
    MPT_APPROVAL_STATUS_ENUM_APPROVAL_HOLD = 12,
    MPT_APPROVAL_STATUS_ENUM_APPROVAL_FIRST_DENIED = 24,
    MPT_APPROVAL_STATUS_ENUM_APPROVAL_SECOND_DENIED = 25,
    MPT_APPROVAL_STATUS_ENUM_APPROVAL_THIRD_DENIED = 26,
    MPT_APPROVAL_STATUS_ENUM_APPROVAL_FOURTH_DENIED = 27,
    MPT_APPROVAL_STATUS_ENUM_APPROVAL_FIFTH_DENIED = 28,


    // VPN Access Type
    VPN_TYPE_ENUM_TEMPORARY = 931,
    VPN_TYPE_ENUM_PERMANENT = 932,

    // Netwok Facility Server Access Access servers Index
    RDP = 0,
    SERVER_ADMIN = 1,
    SSH = 2,
    SMB = 3,
    ACCESS_THROUGH_SQLMANAGEMENT = 4
}
